In [ ]:
#câu 1
a = float (input("nhap gia tri a: "))
b = float (input("nhap gia tri b: "))
print("tong: ", a+b)
print("hieu: ",a-b)
print("tich: ",a*b)
if b!=0:
  print("thuong:",a/b)
else: print("khong the chia cho 0")


nhap gia tri a: 3
nhap gia tri b: 4
tong:  7.0
hieu:  -1.0
tich:  12.0
thuong: 0.75


In [ ]:
#câu 2
s= "hello word"
kq =s[2:5]
print(kq)


llo


In [ ]:
#câu 3
s= "hello wold"
s= s.strip()
print("chữ hoa: ",s.upper())
print(("chữ thường: ",s.lower))
a= s.replace("H","J")
print("sau khi thay thế: ", a)

chữ hoa:  HELLO WOLD
('chữ thường: ', <built-in method lower of str object at 0x7904378a0430>)
sau khi thay thế:  hello wold


In [ ]:
a = float (input("nhap gia tri a: "))
b = float (input("nhap gia tri b: "))
c = float (input("nhap gia tri c: "))
d = float (input("nhap gia tri d: "))
#câu 4
if a>b:
  print("hello word")
#câu 5
if a==b:
  print("yes")
else: print("no")
#câu 6
if a==b:
 print(1)
elif a>b:
  print(2)
else: print(3)
#câu 7
if a==b and b==d:
  print("hello word")
#câu 8
if a==b and c==d:
  print("hello word!")
#câu 9
print('yes') if a>b else print('no')


nhap gia tri a: 6
nhap gia tri b: 6
nhap gia tri c: 5
nhap gia tri d: 5
yes
1
hello word!
no


In [ ]:
#câu 10
a = float (input("nhap gia tri a: "))
b = float (input("nhap gia tri b: "))
print("A") if a>b else print("=") if a==b else print("B")

nhap gia tri a: 5
nhap gia tri b: 6
B


In [ ]:
#câu 11
n = int(input("nhập số phần tử: "))
a = [int(input(f"nhâp phần tử thứ {i+1}:  "))
      for i in range(n)]
b = [x for x in a if x % 2==0]
print("mảng chứa số chẳn", b)

nhập số phần tử: 5
nhâp phần tử thứ 1:  2
nhâp phần tử thứ 2:  3
nhâp phần tử thứ 3:  6
nhâp phần tử thứ 4:  4
nhâp phần tử thứ 5:  8
mảng chứa số chẳn [2, 6, 4, 8]


In [ ]:
#câu 12
tong = sum( x for x in range(1000) if x%3==0 or x%5==0)
print("tổng là: ", tong)

tổng là:  233168


In [ ]:
#câu 13
a= [3,9,1,4]
b= [2,7,4,3,2,8]
kq=[]
max_len = max(len(a),len(b))
for i in range (max_len):
  a1 = a[i] if i<len(a) else 0
  b1 = b[i] if i<len(b) else 0
  kq.append(a1+b1)
print(kq)


[5, 16, 5, 7, 2, 8]


In [ ]:
#câu 14
#a
import random
n = int (input("nhap số cột: "))
m = int (input("nhap số dòng: "))
a=[]
for i in range(m):
  dong =[]
  for j in range(n):
    snn = random.randint(1,100)
    dong.append(snn)
  a.append(dong)
print("ma trận vừa tạo là: ")
for dong in a:
  print(dong)

#b
k= int(input("nhập dòng muốn xuất: "))
if 0<= k<=m:
  print(f"các phần tử thuộc dòng {k}: ",a[k-1])

#c
k= int(input("nhập cột muốn xuất: "))
print(f"các phần tử thuộc cột {k}: ", [row[k-1] for row in a])

#d
max_sum=-1
max_row= 0
for i in range(m):
  tong = sum(a[i])
if tong > max_sum:
  max_sum= tong
  max_row= i
print(f"dòng có tổng lớn nhất là {max_row} với tổng là: ", max_sum)

#e
min_tich = 1
for i in range(m):
    min_tich *= a[i][0]
cot_min = 1
for j in range(1, n):
    tich_hien_tai = 1
    for i in range(m):
        tich_hien_tai *= a[i][j]
    if tich_hien_tai < min_tich:
        min_tich = tich_hien_tai
        cot_min = j
print(f"Cột có tích nhỏ nhất là {cot_min} với tích = {min_tich}")

#f
print("Các phần tử thuộc dong chẳn: ")
for i in range(m):
    if  i%2 ==0:
       print(f"các phần tử thuộc dòng {i}: ",a[i-1])
print("Các phần tử thuộc cột lẻ:")
for j in range(n):
    if j%2 !=0:
       print(f"các phần tử thuộc dòng {j}: ",a[j-1])

#g
tong, dem = 0, 0
for i in range(1, m, 2):
    for x in a[i]:
        if x % 2 == 0:
            tong += x
            dem += 1
    print(f"TBC chẵn dòng lẻ {i}:", tong/dem if dem > 0 else 0)

#h
tong, dem = 0, 0
for i in range(m):
  for j in range(n):
    if i==0 or i==m-1 or j == 0 or j == n - 1:
      tong += a[i][j]
      dem += 1
print("TBC biên: ", tong/dem if dem > 0 else 0)

#i
tong, dem = 0, 0
for i in range(m):
  for j in range(n):
    if i!=0 or i!=m-1 or j != 0 or j != n - 1:
      tong += a[i][j]
      dem += 1
print("TBC các phần tử không thuộc biên: ", tong/dem if dem > 0 else 0)

nhap số cột: 5
nhap số dòng: 4
ma trận vừa tạo là: 
[94, 65, 78, 37, 11]
[37, 80, 60, 87, 15]
[6, 7, 87, 14, 4]
[5, 58, 66, 29, 84]
nhập dòng muốn xuất: 2
các phần tử thuộc dòng 2:  [37, 80, 60, 87, 15]
nhập cột muốn xuất: 1
các phần tử thuộc cột 1:  [94, 37, 6, 5]
dòng có tổng lớn nhất là 3 với tổng là:  242
Cột có tích nhỏ nhất là 4 với tích = 55440
Các phần tử thuộc dong chẳn: 
các phần tử thuộc dòng 0:  [5, 58, 66, 29, 84]
các phần tử thuộc dòng 2:  [37, 80, 60, 87, 15]
Các phần tử thuộc cột lẻ:
các phần tử thuộc dòng 1:  [94, 65, 78, 37, 11]
các phần tử thuộc dòng 3:  [6, 7, 87, 14, 4]
TBC chẵn dòng lẻ 1: 70.0
TBC chẵn dòng lẻ 3: 69.6
TBC biên:  42.07142857142857
TBC các phần tử không thuộc biên:  46.2


In [ ]:
#câu 15
from datetime import date
# a
class SINHVIEN:
    def __init__(self, ma, ten, nam_sinh, dtb):
        self.ma = ma
        self.ten = ten
        self.nam_sinh = nam_sinh
        self.dtb = dtb

# b.
n = int(input("Nhập số lượng sinh viên: "))
ds_sv = []
for i in range(n):
    print(f"--- Nhập thông tin sinh viên thứ {i+1} ---")
    ma = input("Mã sinh viên: ")
    ten = input("Họ tên: ")
    nam_sinh = int(input("Năm sinh: "))
    dtb = float(input("Điểm trung bình: "))
    sv_moi = SINHVIEN(ma, ten, nam_sinh, dtb)
    ds_sv.append(sv_moi)

# c
len_lop = sum(1 for sv in ds_sv if sv.dtb >= 5)
print("Số sinh viên đủ điều kiện lên lớp:",len_lop)

# d
nam_nay = date.today().year
sv_20_tuoi = [sv.ten for sv in ds_sv if nam_nay - sv.nam_sinh >= 20]
print("SV đủ 20 tuổi:", sv_20_tuoi)

# e
sv_dh = [sv for sv in ds_sv if sv.ma[2:4] == "DH"]
print(f"Số SV hệ Đại học: {len(sv_dh)}")

# f
count_lan = sum(1 for sv in ds_sv if sv.ten.split()[-1] == "Lan")
print(f"Số người tên Lan: {count_lan}")

# g
count_phan = sum(1 for sv in ds_sv if sv.ten.startswith("Phan"))
print(f"Số người họ Phan: {count_phan}")


Nhập số lượng sinh viên: 3
--- Nhập thông tin sinh viên thứ 1 ---
Mã sinh viên: 01DH0001
Họ tên: Phan Van Lan
Năm sinh: 2004
Điểm trung bình: 4
--- Nhập thông tin sinh viên thứ 2 ---
Mã sinh viên: 02DH0002
Họ tên: Nguyen Thi Cuc
Năm sinh: 2007
Điểm trung bình: 8
--- Nhập thông tin sinh viên thứ 3 ---
Mã sinh viên: 03CD0003
Họ tên: Phan Hoang Nam
Năm sinh: 2006
Điểm trung bình: 6
Số sinh viên đủ điều kiện lên lớp: 2
SV đủ 20 tuổi: ['Phan Van Lan', 'Phan Hoang Nam']
Số SV hệ Đại học: 2
Số người tên Lan: 1
Số người họ Phan: 2


In [ ]:
#Câu 1 - BTVN
def TronMang(a, b):
    kq = []
    i = 0
    j = 0
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            kq.append(a[i])
        else:
            kq.append(b[j])
        i += 1
        j += 1
    while i < len(a):
        kq.append(a[i])
        i += 1
    while j < len(b):
        kq.append(b[j])
        j += 1
    return kq
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
print("Mảng kết quả:", TronMang(a, b))

Mảng kết quả: [2, 7, 1, 3, 2, 8]


In [4]:
#bài 2 - BTVN
import numpy as np

n = 4
a = np.random.randint(-10, 10, (n, n))
print("Ma trận gốc:\n", a)

# a
tong = 0
for i in range(n):
      for j in range(n):
         if i + j <= n - 1:
            tong += a[i][j]
print("Tổng các phần tử nằm trên tam giác dưới:", tong)

# b
print("Ma trận sau khi chuyển đổi:\n", np.abs(a))

# c
x= int(input("nhập sô nguyên: "))
a[a % 2 == 0] = x
print(f"Ma trận sau khi thay thế số chẳn băng {x}:\n", a)

# d
print("Ma trận có phải toàn chẳn không? ",np.all(a % 2 == 0))

# e
print("Ma trận có đối xứng không? ",np.allclose(a, a.T))

# f
diag_main = np.diag(a)
is_main_inc = np.all(np.diff(diag_main) > 0)
print("Đường chéo chính có tăng dần không? ",is_main_inc)

# g
for i in range(n):
    for j in range(n - 1 - i, n):
        print(a[i][j], end=" ")
    print()

# h
diag_sub = np.diag(np.fliplr(a))
is_sub_dec = np.all(np.diff(diag_sub) < 0)
print("đường chéo phụ có giảm dần không? ",is_sub_dec)

Ma trận gốc:
 [[ -4   0   8   8]
 [ -7  -3  -6  -9]
 [ -1  -7   7   9]
 [ -2 -10   5   5]]
Tổng các phần tử nằm trên tam giác dưới: -14
Ma trận sau khi chuyển đổi:
 [[ 4  0  8  8]
 [ 7  3  6  9]
 [ 1  7  7  9]
 [ 2 10  5  5]]
nhập sô nguyên: 99
Ma trận sau khi thay thế số chẳn băng 99:
 [[99 99 99 99]
 [-7 -3 99 -9]
 [-1 -7  7  9]
 [99 99  5  5]]
Ma trận có phải toàn chẳn không?  False
Ma trận có đối xứng không?  False
Đường chéo chính có tăng dần không?  False
99 
99 -9 
-7 7 9 
99 99 5 5 
đường chéo phụ có giảm dần không?  False


In [5]:
# bài 3 - BTVN
lop_hoc = {
    "sinh_vien_1": {
        "ten": "An",
        "tuoi": 20,
        "diem": 8.5
    },
    "sinh_vien_2": {
        "ten": "Bình",
        "tuoi": 21,
        "diem": 7.0
    },
    "sinh_vien_3": {
        "ten": "Chi",
        "tuoi": 19,
        "diem": 9.2
    }
}
print(lop_hoc["sinh_vien_2"]["ten"])

Bình
